services:
  backend:
    build: ./backend
    container_name: encuestas_backend
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: npm start
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: encuestas_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    command: npm run dev
