services:
  mongodb:
    image: mongo:latest
    container_name: encuestas_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - encuestas_network

  backend:
    build: ./backend
    container_name: encuestas_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/encuestas_db
      - JWT_SECRET=tu_secreto_jwt_super_seguro
    depends_on:
      - mongodb
    networks:
      - encuestas_network

  frontend:
    build: ./frontend
    container_name: encuestas_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - encuestas_network

networks:
  encuestas_network:
    driver: bridge

volumes:
  mongodb_data:
